-- there is no NAMEBOX or ANT key for these so the label ships as str2 like drivers do
ALTER TABLE def_kart_skin ADD COLUMN IF NOT EXISTS display_name VARCHAR(64) NOT NULL DEFAULT '';

UPDATE def_kart_skin SET display_name = 'Black Paint' WHERE name = 'BLACK';
UPDATE def_kart_skin SET display_name = 'Blue Paint' WHERE name = 'BLUE';
UPDATE def_kart_skin SET display_name = 'Green Paint' WHERE name = 'GREEN';
UPDATE def_kart_skin SET display_name = 'Orange Paint' WHERE name = 'ORANGE';
UPDATE def_kart_skin SET display_name = 'Pink Paint' WHERE name = 'PINK';
UPDATE def_kart_skin SET display_name = 'Purple Paint' WHERE name = 'PURPPLE';
UPDATE def_kart_skin SET display_name = 'Red Paint' WHERE name = 'RED';
UPDATE def_kart_skin SET display_name = 'Silver Paint' WHERE name = 'SILVER';
UPDATE def_kart_skin SET display_name = 'Yellow Paint' WHERE name = 'YELLOW';
UPDATE def_kart_skin SET display_name = 'Bone Plate' WHERE name = 'NAMEBOX_001';
UPDATE def_kart_skin SET display_name = 'Blossom Plate' WHERE name = 'NAMEBOX_002';
UPDATE def_kart_skin SET display_name = 'Eyeball Plate' WHERE name = 'NAMEBOX_003';
UPDATE def_kart_skin SET display_name = 'Classic Plate' WHERE name = 'NAMEBOX_004';
UPDATE def_kart_skin SET display_name = 'Pumpkin Plate' WHERE name = 'NAMEBOX_005';
UPDATE def_kart_skin SET display_name = 'Blood Plate' WHERE name = 'NAMEBOX_006';
UPDATE def_kart_skin SET display_name = 'Frost Plate' WHERE name = 'NAMEBOX_007';
UPDATE def_kart_skin SET display_name = 'Skull Plate' WHERE name = 'NAMEBOX_008';
UPDATE def_kart_skin SET display_name = 'Speed Tag' WHERE name = 'NAMEBOX_009';
UPDATE def_kart_skin SET display_name = 'Slowpoke Tag' WHERE name = 'NAMEBOX_010';
UPDATE def_kart_skin SET display_name = 'Chrome Oval' WHERE name = 'NAMEBOX_011';
UPDATE def_kart_skin SET display_name = 'Sweet Bone' WHERE name = 'NAMEBOX_012';
UPDATE def_kart_skin SET display_name = 'Gold Slab' WHERE name = 'NAMEBOX_013';
UPDATE def_kart_skin SET display_name = 'GM Plate' WHERE name = 'NAMEBOX_014';
UPDATE def_kart_skin SET display_name = 'First Place' WHERE name = 'NAMEBOX_015';
UPDATE def_kart_skin SET display_name = 'Second Place' WHERE name = 'NAMEBOX_016';
UPDATE def_kart_skin SET display_name = 'Third Place' WHERE name = 'NAMEBOX_017';
UPDATE def_kart_skin SET display_name = 'Star Bone' WHERE name = 'NAMEBOX_018';
UPDATE def_kart_skin SET display_name = 'Crest Plate' WHERE name = 'NAMEBOX_019';
UPDATE def_kart_skin SET display_name = 'Oskart Plate' WHERE name = 'NAMEBOX_020';
UPDATE def_kart_skin SET display_name = 'Ghost Hood' WHERE name = 'ANT_01';
UPDATE def_kart_skin SET display_name = 'Pink Ribbon' WHERE name = 'ANT_02';
UPDATE def_kart_skin SET display_name = 'Sheep Balloon' WHERE name = 'ANT_03';
UPDATE def_kart_skin SET display_name = 'Chocolate Donut' WHERE name = 'ANT_04';
UPDATE def_kart_skin SET display_name = 'Happy Cat' WHERE name = 'ANT_05';
UPDATE def_kart_skin SET display_name = 'Sunflower' WHERE name = 'ANT_06';
UPDATE def_kart_skin SET display_name = 'Frozen Heart' WHERE name = 'ANT_07';
UPDATE def_kart_skin SET display_name = 'Butterfly' WHERE name = 'ANT_08';
UPDATE def_kart_skin SET display_name = 'Green Shell' WHERE name = 'ANT_10';
UPDATE def_kart_skin SET display_name = 'Union Jack' WHERE name = 'ANT_11';
UPDATE def_kart_skin SET display_name = 'France Flag' WHERE name = 'ANT_12';
UPDATE def_kart_skin SET display_name = 'Germany Flag' WHERE name = 'ANT_13';
UPDATE def_kart_skin SET display_name = 'Spain Flag' WHERE name = 'ANT_14';
UPDATE def_kart_skin SET display_name = 'Sunset Flag' WHERE name = 'ANT_15';
UPDATE def_kart_skin SET display_name = 'Flying Saucer' WHERE name = 'ANT_16';
UPDATE def_kart_skin SET display_name = 'Pirate Banner' WHERE name = 'ANT_17';
UPDATE def_kart_skin SET display_name = 'Red Megaphone' WHERE name = 'ANT_18';
UPDATE def_kart_skin SET display_name = 'Jingle Bell' WHERE name = 'ANT_23';
UPDATE def_kart_skin SET display_name = 'Christmas Boot' WHERE name = 'ANT_24';
UPDATE def_kart_skin SET display_name = 'Chrome Ball' WHERE name = 'ANT_25';
UPDATE def_kart_skin SET display_name = 'Brazil Flag' WHERE name = 'ANT_26';
UPDATE def_kart_skin SET display_name = 'Kenya Flag' WHERE name = 'ANT_27';
UPDATE def_kart_skin SET display_name = 'Nigeria Flag' WHERE name = 'ANT_28';
UPDATE def_kart_skin SET display_name = 'South Africa Flag' WHERE name = 'ANT_29';
UPDATE def_kart_skin SET display_name = 'UAE Flag' WHERE name = 'ANT_30';
UPDATE def_kart_skin SET display_name = 'Uganda Flag' WHERE name = 'ANT_31';
UPDATE def_kart_skin SET display_name = 'Party Flag' WHERE name = 'ANT_32';
UPDATE def_kart_skin SET display_name = 'Soccer Ball' WHERE name = 'ANT_33';
