-- 019 kart and driver labels straight out of the client string table
ALTER TABLE vehicle_templates ADD COLUMN IF NOT EXISTS title_key VARCHAR(48) NOT NULL DEFAULT '';
ALTER TABLE vehicle_templates ADD COLUMN IF NOT EXISTS info_key  VARCHAR(48) NOT NULL DEFAULT '';
ALTER TABLE drivers ADD COLUMN IF NOT EXISTS info_key VARCHAR(48) NOT NULL DEFAULT '';

UPDATE vehicle_templates SET title_key='CAR_BASIC_1_TITLE', info_key='CAR_BASIC_1_INFO' WHERE id=10010;
UPDATE vehicle_templates SET title_key='CAR_BASIC_2_TITLE', info_key='CAR_BASIC_2_INFO' WHERE id=10011;
UPDATE vehicle_templates SET title_key='CAR_BASIC_3_TITLE', info_key='CAR_BASIC_3_INFO' WHERE id=10012;
UPDATE vehicle_templates SET title_key='CAR_BASIC_4_TITLE', info_key='CAR_BASIC_4_INFO' WHERE id=10013;
UPDATE vehicle_templates SET title_key='CAR_BASIC_5_TITLE', info_key='CAR_BASIC_5_INFO' WHERE id=10014;
UPDATE vehicle_templates SET title_key='CAR_BASIC_6_TITLE', info_key='CAR_BASIC_6_INFO' WHERE id=10015;
UPDATE vehicle_templates SET title_key='CAR_BIKE_01_TITLE', info_key='CAR_BIKE_01_INFO' WHERE id=10101;
UPDATE vehicle_templates SET title_key='CAR_BIKE_02_TITLE', info_key='CAR_BIKE_02_INFO' WHERE id=10102;
UPDATE vehicle_templates SET title_key='CAR_BIKE_03_TITLE', info_key='CAR_BIKE_03_INFO' WHERE id=10103;
UPDATE vehicle_templates SET title_key='CAR_BIKE_03_ONGAME_TITLE', info_key='CAR_BIKE_03_ONGAME_INFO' WHERE id=10104;
UPDATE vehicle_templates SET title_key='CAR_BIKE_04_TITLE', info_key='CAR_BIKE_04_INFO' WHERE id=10105;
UPDATE vehicle_templates SET title_key='CAR_BIKE_05_TITLE', info_key='CAR_BIKE_05_INFO' WHERE id=10106;
UPDATE vehicle_templates SET title_key='CAR_BIKE_06_TITLE', info_key='CAR_BIKE_06_INFO' WHERE id=10107;
UPDATE vehicle_templates SET title_key='CAR_CITROEN_TITLE', info_key='CAR_CITROEN_INFO' WHERE id=11001;
UPDATE vehicle_templates SET title_key='CAR_KONA_TITLE', info_key='CAR_KONA_INFO' WHERE id=11002;
UPDATE vehicle_templates SET title_key='CAR_MINI_TITLE', info_key='CAR_MINI_INFO' WHERE id=11003;
UPDATE vehicle_templates SET title_key='CAR_MINI_ONGAME_TITLE', info_key='CAR_MINI_ONGAME_INFO' WHERE id=11004;
UPDATE vehicle_templates SET title_key='CAR_DS_01_TITLE', info_key='CAR_DS_01_INFO' WHERE id=11101;
UPDATE vehicle_templates SET title_key='CAR_QD_01_TITLE', info_key='CAR_QD_01_INFO' WHERE id=11201;
UPDATE vehicle_templates SET title_key='CAR_QD_02_TITLE', info_key='CAR_QD_02_INFO' WHERE id=11202;
UPDATE vehicle_templates SET title_key='CAR_RB_01_TITLE', info_key='CAR_RB_01_INFO' WHERE id=11301;
UPDATE vehicle_templates SET title_key='CAR_RB_02_TITLE', info_key='CAR_RB_02_INFO' WHERE id=11302;
UPDATE vehicle_templates SET title_key='CAR_FR_01_TITLE', info_key='CAR_FR_01_INFO' WHERE id=11401;
UPDATE vehicle_templates SET title_key='CAR_FR_02_TITLE', info_key='CAR_FR_02_INFO' WHERE id=11402;
UPDATE vehicle_templates SET title_key='CAR_FR_03_TITLE', info_key='CAR_FR_03_INFO' WHERE id=11403;
UPDATE vehicle_templates SET title_key='CAR_FR_04_TITLE', info_key='CAR_FR_04_INFO' WHERE id=11404;
UPDATE vehicle_templates SET title_key='CAR_FR_05_TITLE', info_key='CAR_FR_05_INFO' WHERE id=11405;
UPDATE vehicle_templates SET title_key='CAR_CHASSIS_03_TITLE', info_key='CAR_CHASSIS_03_INFO' WHERE id=12002;
UPDATE vehicle_templates SET title_key='CAR_CHASSIS_05_TITLE', info_key='CAR_CHASSIS_05_INFO' WHERE id=12003;
UPDATE vehicle_templates SET title_key='CAR_CHASSIS_02_TITLE', info_key='CAR_CHASSIS_02_INFO' WHERE id=12004;
UPDATE vehicle_templates SET title_key='CAR_CHASSIS_01_TITLE', info_key='CAR_CHASSIS_01_INFO' WHERE id=12005;
UPDATE vehicle_templates SET title_key='CAR_CHASSIS_04_TITLE', info_key='CAR_CHASSIS_04_INFO' WHERE id=12006;
UPDATE vehicle_templates SET title_key='CAR_THUNDER_TITLE', info_key='CAR_THUNDER_INFO' WHERE id=12007;
UPDATE vehicle_templates SET title_key='CAR_TANK_TITLE', info_key='CAR_TANK_INFO' WHERE id=12008;
UPDATE vehicle_templates SET title_key='CAR_TOILET_TITLE', info_key='CAR_TOILET_INFO' WHERE id=12009;
UPDATE vehicle_templates SET title_key='CAR_OSKART_TITLE', info_key='CAR_OSKART_INFO' WHERE id=12010;
UPDATE vehicle_templates SET title_key='CAR_HALLOWEEN_TITLE', info_key='CAR_HALLOWEEN_INFO' WHERE id=13001;
UPDATE vehicle_templates SET title_key='CAR_PUMPKIN_TITLE', info_key='CAR_PUMPKIN_INFO' WHERE id=13002;
UPDATE vehicle_templates SET title_key='CAR_MUMMY_TITLE', info_key='CAR_MUMMY_INFO' WHERE id=13003;
UPDATE vehicle_templates SET title_key='CAR_WITCH_TITLE', info_key='CAR_WITCH_INFO' WHERE id=13004;
UPDATE vehicle_templates SET title_key='CAR_WOLF_TITLE', info_key='CAR_WOLF_INFO' WHERE id=13005;
UPDATE vehicle_templates SET title_key='CAR_PRINCE_TITLE', info_key='CAR_PRINCE_INFO' WHERE id=13006;
UPDATE vehicle_templates SET title_key='CAR_PRINCESS_TITLE', info_key='CAR_PRINCESS_INFO' WHERE id=13007;
UPDATE vehicle_templates SET title_key='CAR_MONSTER_TITLE', info_key='CAR_MONSTER_INFO' WHERE id=13008;
UPDATE vehicle_templates SET title_key='CAR_YUK_TITLE', info_key='CAR_YUK_INFO' WHERE id=13009;
UPDATE vehicle_templates SET title_key='CAR_Rudolf_01_TITLE', info_key='CAR_Rudolf_01_INFO' WHERE id=13010;

UPDATE drivers SET info_key='DRIVER_MUMMY_INFO' WHERE id=5;
UPDATE drivers SET info_key='DRIVER_COSMO_INFO' WHERE id=6;
UPDATE drivers SET info_key='DRIVER_MORIKO_INFO' WHERE id=7;
UPDATE drivers SET info_key='DRIVER_PRINCE_INFO' WHERE id=8;
UPDATE drivers SET info_key='DRIVER_PRINCESS_INFO' WHERE id=9;
UPDATE drivers SET info_key='DRIVER_PUMPKIN_INFO' WHERE id=10;
UPDATE drivers SET info_key='DRIVER_WITCH_INFO' WHERE id=11;
UPDATE drivers SET info_key='DRIVER_WOLF_INFO' WHERE id=12;
UPDATE drivers SET info_key='DRIVER_MONSTER_INFO' WHERE id=13;
UPDATE drivers SET info_key='DRIVER_YUK_INFO' WHERE id=14;
